name: Dart CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pub get
    - name: Run tests
      run: |
        pub run test lib/util/test/ip_range_test.dart
    - name: Compile binary
      run: dart2native .\bin\scp_client.dart -o .\scp_client
