name: Linux Build

on: push

jobs:
  build-linux:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pub get
    - name: Run dart analyze
      run: |
        dart analyze
  